### ISSUE TITLE
"undefined" for RO-Crate profile

### ISSUE THREAD

**Issue by stain** [UTS-eResearch/ro-crate-html-js#10]
In https://datasciencehub.net/system/files/ds-supplementary-706-1128.html#ro-crate-metadata.json we see "conformsTo: undefined".

This is caused by the metadata file descriptor not having a corresponding contextual entity for the RO-Crate standard itself, that is we have:

```json
    {
      "@id": "ro-crate-metadata.json",
      "@type": "CreativeWork",
      "conformsTo": {
        "@id": "https://w3id.org/ro/crate/1.1"
      },
      "about": {
        "@id": "./"
      },
      "creator": {
        "@id": "https://orcid.org/0000-0001-9842-9718"
      },
      "license": {
        "@id": "https://spdx.org/licenses/CC0-1.0"
      }
    },
```

but no entity for `https://w3id.org/ro/crate/1.1`.

The RO-Crate specification does not require or even suggest an entity for `https://w3id.org/ro/crate/1.1` (although that may be important for RO-Crate 1.2 for consistancy with [profile entities](https://www.researchobject.org/ro-crate/1.2-DRAFT/profiles#declaring-conformance-of-an-ro-crate-profile)).

So I think this is a bug in rochtml as it should just show the URL if there is no contextual entity.

Likewise rochtml may be sensitive if there is an entity that has not got a `@type` and `name` - perhaps we should make more explicit in RO-Crate spec that this is expected.

**Comment by ptsefton** [comment]
I have pushed a new version of the library and the rendering code - can you check please @stain.
